### ISSUE TITLE
Sonata Admin CUSTOM ADMIN ACTION problem

### ISSUE THREAD

**Issue by featuriz** [pix-digital/pixSortableBehaviorBundle#48]
As per Soanta Admin doc for SORTABLE BEHAVIOR IN ADMIN LISTING at [link](https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_sortable_listing.html)

```
services:
    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Clients" }
        arguments:
            - ~
            - AppBundle\Entity\Client
            - 'PixSortableBehaviorBundle:SortableAdmin' # define the new controller via the third argument

```
And for creating [CREATING A CUSTOM ADMIN ACTION](https://sonata-project.org/bundles/admin/2-3/doc/cookbook/recipe_custom_action.html) at Sonata Admin

```
services:
    acme.demo.admin.car:
        class: Acme\DemoBundle\Admin\CarAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Demo, label: Car }
        arguments:
            - null
            - Acme\DemoBundle\Entity\Car
            - AcmeDemoBundle:CRUD
```

In both cases THIRD ARGUMENTS is used. How to overcome this issue

**Comment by aliocza** [comment]
Hi,
You can extends the controller SortableAdminController from pixSortableBehaviorBundle (he extends CRUDController) : 

```
// AppBundle/Controller/CRUDController.php
namespace AppBundle\Controller;

// ...
use Pix\SortableBehaviorBundle\Controller\SortableAdminController as ControllerExt;

class CRUDController extends ControllerExt
{
   //your custom code
}
```
```
services:
    app.admin.client:
        class: AppBundle\Admin\ClientAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Clients" }
        arguments:
            - ~
            - AppBundle\Entity\Client
            - 'AppBundle:CRUD' # define the new controller via the third argument
```
